name: DailyQuests
version: '1.0-SNAPSHOT'
main: org.elementcraft.dailyQuests.DailyQuests
api-version: '1.16'
depend: [Vault]

commands:
  daily:
    description: Main Daily command
    permission: daily.use

permissions:
  trap.*:
    default: true